### PR TITLE
🔥[Urgent] Fix dcli issue when `get create project`

### PR DESCRIPTION
**Pull request by knottx**
Fix dcli issue when `get create project` and update dependencies

For people who are waiting for this 
you can use my repository for now
```cmd
dart pub global deactivate get_cli

dart pub global activate -s git https://github.com/knottx/get_cli.git --git-ref knottx
```

### CODE REVIEW

**Comment by knottx** [comment]
@jonataslaw @CpdnCristiano hope you are both well.

**Comment by olipiskandar** [comment]
@jonatanslaw
please accpet this PR

**Comment by CpdnCristiano** [comment]
@olipiskandar Thank you!

**Comment by nisone** [comment]
Thank you

**Pull request merged**
